version: "3.1"

networks:
  proxy-net:
    external:
      name: proxy-net

services:
  cocoa-rocks:
    container_name: cocoa-rocks
    networks:
      - proxy-net
    restart: always
    build: .
    environment:
      - VIRTUAL_HOST=cocoa.rocks
      - LETSENCRYPT_HOST=cocoa.rocks
      - LETSENCRYPT_EMAIL=mail@viktor-braun.de
      
      